version: '1.0'
services:
  redis:
    image: redis:6.2-alpine
    container_name: myRedis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'

volumes:
  redis_data:
    driver: local